# Site Settings
title:               NBA Super Stars
tagline:             a miniproject for STA 141B
description:
baseurl:            #"/STA141Btest"
url:                #"https://wurl2013.github.io"
github:
  url:               #"https://wurl2013.github.io/STA141Btest/"
author:
  name:              "Wu"
  email:             "rlwu@ucdavis.edu"
  twitter:          # "paululele"
  instagram:        # "paululele"
  github:           # "lenpaul"
  facebook:         # "Le.Paul.94"
  linkedin:         # "lenpaul"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]

theme: jekyll-theme-cayman